export const FETCHCOMMENT_REQUEST_START = "FETCHCOMMENT_REQUEST_START";
export const FETCHCOMMENT_REQUEST_SUCCESS = "FETCHCOMMENT_REQUEST_SUCCESS";
export const FETCHCOMMENT_REQUEST_FAIL = "FETCHCOMMENT_REQUEST_FAIL";